name: Publish VSCode Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: 🧩 Checkout
        uses: actions/checkout@v4

      - name: 🧱 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Install deps
        run: npm ci

      - name: 🔧 Compile TypeScript
        run: npm run compile

      - name: 🔎 Read package version
        id: pkgver
        run: |
          VER=$(node -p "require('./package.json').version")
          echo "ver=$VER" >> "$GITHUB_OUTPUT"

      - name: 📀 Package VSIX
        run: npx @vscode/vsce package --out mtl-ddex-vscode-helper-${{ steps.pkgver.outputs.ver }}.vsix

      - name: 🚀 Publish to Marketplace
        run: npx @vscode/vsce publish --packagePath mtl-ddex-vscode-helper-${{ steps.pkgver.outputs.ver }}.vsix -p "$VSCE_PAT"
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}

      - name: 💾 Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: mtl-ddex-vscode-helper-${{ steps.pkgver.outputs.ver }}.vsix